import './globals.css'
import Link from 'next/link'
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  navigationMenuTriggerStyle
} from "@/components/ui/navigation-menu"
import React from "react";

export const metadata = {
  title: 'CLIC CHAT',
  description: 'Generated by create next app',
}

const paths = [
  {href: '/', label: 'Home'},
  {href: '/search', label: 'Search'},
]

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className="w-full">
    <NavigationMenu className="w-full m-2">
      {paths.map(({href, label}) => (
        <NavigationMenuItem className="list-none" key={href}>
          <Link href={href} legacyBehavior passHref>
            <NavigationMenuLink className={navigationMenuTriggerStyle()}>
              {label}
            </NavigationMenuLink>
          </Link>
        </NavigationMenuItem>
      ))}

    </NavigationMenu>
    {children}</body>
    </html>
  )
}
